Controllers/AdminOpController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Projeto_Lab_Web_Grupo3.Models;
using Projeto_Lab_Web_Grupo3.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Projeto_Lab_Web_Grupo3.Data;
using Microsoft.EntityFrameworkCore;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace Projeto_Lab_Web_Grupo3.Controllers
{
    public class AdminOpController : Controller
    {

        private readonly Projeto_Lab_WebContext bd;
        private readonly IEmailSender _emailSender;
        

        public AdminOpController(IEmailSender emailSender, IWebHostEnvironment env, Projeto_Lab_WebContext context)
        {
            bd = context;
            _emailSender = emailSender;
           
        }

        [Authorize(Roles = "Administrador,Operador")]
        public async Task<IActionResult> Index()
        {

            var contratos = await bd.Contratos.ToListAsync();
            var emailenviado = await bd.EnvioDeFaturas.ToListAsync();

            DateTime hoje = DateTime.Today;
            DateTime mespassado = hoje.AddMonths(-1);
            int mes = mespassado.Month;
            int ano = mespassado.Year;

            bool enviado = false;

            foreach (var item in emailenviado)
            {
                if (item.mes == mes && item.ano==ano)
                {
                    enviado = true;
                }
                else
                {
                    enviado = false;
                }
            }

            if(enviado==false)
            {
                string email; string assunto; string mensagem;
                foreach (var item in bd.Contratos)
      
                {
                    var cliente = await bd.Utilizadores.FirstOrDefaultAsync(m => m.UtilizadorId == item.UtilizadorId);
                    decimal preco = item.PrecoFinal;
                    email = cliente.Email;

                    string NomeMes = NomesDoMes(mes);
                    assunto = "Faturação RD Telecom";
                    mensagem = "Caro/a cliente, informamos que tem a pagar " + preco + "€ da fatura de " + NomeMes + ". Obrigado pela sua preferência!";

                    try
                    {
                        //email destino, assunto do email, mensagem a enviar
                        await _emailSender.SendEmailAsync(email, assunto, mensagem);

                        enviado = true;
                    }
                    catch (Exception)
                    {
                        enviado = false;
                    }
                }

                emailenviado.Add(new EnvioDeFaturas() { DataDeEnvio = DateTime.Today, Enviado = true, mes = mes, ano = ano });
                foreach (var item in emailenviado)
                {
                    bd.EnvioDeFaturas.Add(item);
                }
                await bd.SaveChangesAsync();

            }

            List<InfoPacoteViewModel> ListaPacotes = new List<InfoPacoteViewModel>();

            foreach (var pacote in bd.Pacotes)
            {
                InfoPacoteViewModel infoPacote = new InfoPacoteViewModel();

                infoPacote.Pacote = pacote;

                infoPacote.Promocao = await bd.PromocoesPacotes
                    .Include(p => p.Promocoes)
                    .Where(p => p.PacoteId == pacote.PacoteId)
                    .Select(p => p.Promocoes)
                    .Where(p => p.DataInicio < DateTime.Now && p.DataFim > DateTime.Now)
                    .FirstOrDefaultAsync();

                infoPacote.Servicos = await bd.ServicosPacotes
                    .Include(p => p.Servico)
                    .Where(p => p.PacoteId == pacote.PacoteId)
                    .Select(p => p.Servico)
                    .ToListAsync();

                foreach(var item in infoPacote.Servicos)
                {
                    infoPacote.TiposServicos = await bd.Servicos
                    .Include(p => p.TipoServicos)
                    .Where(p => p.ServicoId == item.ServicoId)
                    .Select(p => p.TipoServicos)
                    .ToListAsync();
                }
                

                ListaPacotes.Add(infoPacote);
            }

            var Funcionarios = bd.Utilizadores.Where(p => p.Role != "Cliente").ToList();
            int contagemFunc = Funcionarios.Count();

            var Clientes = bd.Utilizadores.Where(p => p.Role == "Cliente").ToList();
            int contagemClientes = Clientes.Count();

            var Contratos = bd.Contratos.ToList();
            int contagemContratos = Contratos.Count();

            var Reclamacoes = bd.Reclamacoes.Where(r =>r.Inactivo == false).ToList();
            int contagemReclamacoes = Reclamacoes.Count();

            var Reclamacoes1 = bd.Reclamacoes.Where(r => r.Inactivo == true).ToList();
            int reclamacoesfechadas = Reclamacoes1.Count();
           

            decimal receita = 0;
            foreach (var item in Contratos)
            {
                receita += item.PrecoFinal;
            }


            if (User.IsInRole("Operador"))
            {
                var funcionario = bd.Utilizadores.SingleOrDefault(c => c.Email == User.Identity.Name);


                List<Contratos> MeusContratos = await bd.Contratos
                    .Where(p => p.FuncionarioId == funcionario.UtilizadorId)
                    .ToListAsync();
                int contagemMeusContratos = MeusContratos.Count();


                //DateTime now = DateTime.Now;
                //var startDate = new DateTime(now.Year, now.Month, 1);
                //var endDate = startDate.AddMonths(1).AddDays(-1);
                decimal faturacao = 0;
                foreach (var item in MeusContratos)
                {
                    
                    faturacao += item.PrecoFinal;

                }
                ViewData["faturacao"] = faturacao;
                ViewData["Meuscontratos"] = contagemMeusContratos;

            }


            HomeGestaoViewModel modelo = new HomeGestaoViewModel
            {
                enviado = enviado,
                Pacotes = ListaPacotes,
            };
            
            ViewData["clientes"] = contagemClientes;
            ViewData["contratos"] = contagemContratos;
            ViewData["receita"] = receita;
            ViewData["func"] = contagemFunc;
            ViewData["reclamacoes"] = contagemReclamacoes;
            ViewData["reclamacoesfechadas"] = reclamacoesfechadas;


            return View(modelo);
        }

        [Authorize(Roles = "Administrador,Operador")]
        public async Task<IActionResult> ContaPessoal(int ano)
        {
            DateTime hoje = DateTime.Today;
            int anoCorrente = hoje.Year;
            if (ano == 0)
            {
                ano = anoCorrente;
            }
            var funcionario = bd.Utilizadores.SingleOrDefault(c => c.Email == User.Identity.Name);

            List<FaturacaoOperadores> faturacaoDoOperador = await bd.FaturacaoOperadores
                .Where(p => p.UtilizadorId == funcionario.UtilizadorId)
                .OrderBy(p => p.Ano)
                .ThenBy(p => p.Mes)
                .ToListAsync();

            var PrimeiroContrato = faturacaoDoOperador.First();
            int PrimeiroAno = PrimeiroContrato.Ano;

            List<int> Anos = new List<int>();
            for (int i = PrimeiroAno; i <= anoCorrente; i++)
            {
                Anos.Add(i);
            }

            ViewData["Anos"] = new SelectList(Anos);

            List<FaturacaoOperadores> faturacaoDoOperadorPorAno = await bd.FaturacaoOperadores
                .Where(p => p.UtilizadorId == funcionario.UtilizadorId && p.Ano == ano)
                .OrderBy(p => p.Ano)
                .ThenBy(p=> p.Mes)
                .ToListAsync();

            ViewData[ "PrimeiroAno"] = faturacaoDoOperador[0].Ano;
            ViewData["AnoCorrente"] = DateTime.Now.Year;

            var distrito = bd.Distritos.SingleOrDefault(c => c.DistritosId == funcionario.DistritosId);


            FaturacaoMensalViewModel faturacaoMensalViewModel = new FaturacaoMensalViewModel
            {
                distrito = distrito,
                funcionario = funcionario,
                faturacaoOperadores = faturacaoDoOperadorPorAno,
                ano = ano
            };

            return View(faturacaoMensalViewModel);
        }

        [Authorize(Roles = "Administrador,Operador")]
        public async Task<IActionResult> FaturacaoMensalOperador(int ano)
        {
            DateTime hoje = DateTime.Today;
            int anoCorrente = hoje.Year;
            if (ano == 0)
            {
                ano = anoCorrente;
            }
            var funcionario = bd.Utilizadores.SingleOrDefault(c => c.Email == User.Identity.Name);

            List<FaturacaoOperadores> faturacaoDoOperador = await bd.FaturacaoOperadores
                .Where(p => p.UtilizadorId == funcionario.UtilizadorId)
                .OrderBy(p => p.Ano)
                .ThenBy(p => p.Mes)
                .ToListAsync();

            var PrimeiroContrato = faturacaoDoOperador.First();
            int PrimeiroAno = PrimeiroContrato.Ano;

            List<int> Anos = new List<int>();
            for (int i = PrimeiroAno; i <= anoCorrente; i++)
            {
                Anos.Add(i);
            }

            ViewData["Anos"] = new SelectList(Anos);

            List<FaturacaoOperadores> faturacaoDoOperadorPorAno = await bd.FaturacaoOperadores
                .Where(p => p.UtilizadorId == funcionario.UtilizadorId && p.Ano == ano)
                .OrderBy(p => p.Ano)
                .ThenBy(p => p.Mes)
                .ToListAsync();

            ViewData["PrimeiroAno"] = faturacaoDoOperador[0].Ano;
            ViewData["AnoCorrente"] = DateTime.Now.Year;

Views/AdminOp/ContaPessoal.cshtml
@model FaturacaoMensalViewModel

@{
    ViewData["Title"] = "Faturação Mensal";
    Layout = "_LayoutAdmin";
}

<body>
    <!-- container section start -->
    <section id="container" class="">
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <h3 class="page-header"><i class="fa fa-user-md"></i> Conta Pessoal</h3>
                        <ol class="breadcrumb">
                            <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>
                         
                            <li><i class="fa fa-user-md"></i>Conta Pessoal</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <!-- profile-widget -->
                    <div class="col-lg-12">
                        <div class="profile-widget profile-widget-info">
                            <div class="panel-body">
                                <div class="col-lg-2 col-sm-2">
                                    <h4>@Model.funcionario.Nome</h4>
                                    <div class="follow-ava">
                                        <img src="~/images/operator.png" alt="">
                                    </div>
                                    <h6>@Model.funcionario.Role</h6>
                                </div>
                                <div class="col-lg-4 col-sm-4 follow-info">
                                    <p><i class="icon_pin_alt"></i>@Model.distrito.Nome</p>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <!-- page start-->
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading tab-bg-info">
                                <ul class="nav nav-tabs">
                                    <li class="active">
                                        <a data-toggle="tab" href="#perfil">
                                            <i class="icon-user"></i>
                                            Perfil
                                        </a>
                                    </li>

                                    <li>
                                        <a asp-area="" asp-controller="AdminOp" asp-action="FaturacaoMensalOperador">
                                            <i class="icon-home"></i>
                                            Faturação Mensal
                                        </a>
                                    </li>
                                    <li class="">
                                        <a asp-area="" asp-controller="Utilizadores" asp-action="EditFuncionarios" asp-route-id="@Model.funcionario.UtilizadorId">
                                            <i class="icon-envelope"></i>
                                            Atualizar Dados Pessoais
                                        </a>
                                    </li>
                                </ul>
                            </header>
                            <div class="panel-body">
                                <div class="tab-content">
                                    <div id="perfil" class="tab-pane active">
                                        <section class="panel">

                                            <div class="panel-body bio-graph-info">
                                                <h1>Perfil</h1>
                                                <div class="row">
                                                    <div class="bio-row">
                                                        <p><span>Nome </span>: @Model.funcionario.Nome </p>
                                                    </div>

                                                    <div class="bio-row">
                                                        <p><span>Data de Nascimento</span>: @Model.funcionario.DataNascimento </p>
                                                    </div>
                                                    <div class="bio-row">
                                                        <p><span>Morada </span>: @Model.funcionario.Morada </p>
                                                    </div>
                                                    <div class="bio-row">
                                                        <p><span>Código Postal </span>: @Model.funcionario.CodigoPostal</p>
                                                    </div>
                                                    <div class="bio-row">
                                                        <p><span>Código Postal </span>: @Model.distrito.Nome</p>
                                                    </div>
                                                    <div class="bio-row">
                                                        <p><span>Email </span>: @Model.funcionario.Email</p>
                                                    </div>
                                                    <div class="bio-row">
                                                        <p><span>Telefone </span>: @Model.funcionario.Telemovel</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </section>
                                    </div>

                                   
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </section>
        </section>
    </section>
    </section>
    </section>
</body>

Views/AdminOp/FaturacaoMensalOperador.cshtml
@model FaturacaoMensalViewModel

@{
    ViewData["Title"] = "Faturação Mensal";
    Layout = "_LayoutAdmin";
}

<body>
    <!-- container section start -->
    <section id="container" class="">
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <h3 class="page-header"><i class="fa fa-user-md"></i> Conta Pessoal</h3>
                        <ol class="breadcrumb">
                            <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>

                            <li><i class="fa fa-user-md"></i>Conta Pessoal</li>
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <!-- profile-widget -->
                    <div class="col-lg-12">
                        <div class="profile-widget profile-widget-info">
                            <div class="panel-body">
                                <div class="col-lg-2 col-sm-2">
                                    <h4>@Model.funcionario.Nome</h4>
                                    <div class="follow-ava">
                                        <img src="~/images/operator.png" alt="">
                                    </div>
                                    <h6>@Model.funcionario.Role</h6>
                                </div>
                                <div class="col-lg-4 col-sm-4 follow-info">
                                    <p><i class="icon_pin_alt"></i>@Model.distrito.Nome</p>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <!-- page start-->
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading tab-bg-info">
                                <ul class="nav nav-tabs">
                                    <li >
                                        <a asp-area="" asp-controller="AdminOp" asp-action="ContaPessoal">
                                            <i class="icon-user"></i>
                                            Perfil
                                        </a>
                                    </li>

                                    <li class="active">
                                        <a asp-area="" asp-controller="AdminOp" asp-action="FaturacaoMensalOperador">
                                            <i class="icon-home"></i>
                                            Faturação Mensal
                                        </a>
                                    </li>
                                    <li class="">
                                        <a asp-area="" asp-controller="Utilizadores" asp-action="EditFuncionarios" asp-route-id="@Model.funcionario.UtilizadorId">
                                            <i class="icon-envelope"></i>
                                            Atualizar Dados Pessoais
                                        </a>
                                    </li>
                                </ul>
                            </header>
                            <div class="panel-body">
                                <div class="tab-content">
                                   
                                    <div id="faturacaomensal" class="tab-pane active">
                                        <section class="panel">
                                            <div class="col-sm-6">
                                                <form asp-action="FaturacaoMensalOperador" method="get">
                                                    <div class="form-group">
                                                        <p>Selecione o ano de faturação que pretende consultar</p>
                                                        <select asp-for="ano" class="form-control" asp-items="ViewBag.Anos"></select>
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="submit" value="Mostrar" class="btn btn-primary" />
                                                    </div>
                                                </form>
                                                <h4>Faturação do ano @Model.ano</h4>
                                                <table class="table">
                                                    <thead>
                                                        <tr>
                                                            <th>Mês</th>
                                                            <th>Faturação</th>

                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model.faturacaoOperadores)
                                                        {
                                                            {
                                                                <tr>
                                                                    <td> @item.NomeMes</td>
                                                                    <td> @item.TotalFaturacao</td>

                                                                </tr>
                                                            }
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                        </section>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </section>
        </section>
    </section>
    </section>
    </section>
</body>

Views/AdminOp/Index.cshtml
@model HomeGestaoViewModel

@{
    Layout = "_LayoutAdmin";

}

<!--main content start-->
<section id="main-content">

    <section class="wrapper">
        <!--overview start-->
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><i class="fa fa-laptop"></i> Bem-vindo/a</h3>
            </div>
        </div>
        <div class=" row">
            @if (Model.enviado == true)
            {
                <div class="panel-body">
                    <div class="alert alert-success fade in">
                        <button data-dismiss="alert" class="close close-sm" type="button">
                            <i class="icon-remove"></i>
                        </button>
                        As faturas do mês passado já foram enviadas!
                    </div>
                </div>
            }
            @if (Model.enviado == false)
            {
        <div class="alert alert-block alert-danger fade in">
            <button data-dismiss="alert" class="close close-sm" type="button">
                <i class="icon-remove"></i>
            </button>
            <strong>Erro</strong> O envio das faturas do mês passado falhou. Contacte a assistência
        </div>
            }

        </div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <div class="info-box purple-bg">
                    <i class="fas fa-briefcase"></i>
                    <div class="count">@ViewBag.func</div>
                    <div class="title">Funcionários</div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <div class="info-box blue-bg">
                    <i class="fas fa-users"></i>
                    <div class="count">@ViewBag.clientes</div>
                    <div class="title">Clientes</div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <div class="info-box brown-bg">
                    <i class="far fa-file-alt"></i>
                    <div class="count">@ViewBag.contratos</div>
                    <div class="title">Contratos</div>
                </div>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <div class="info-box green-bg">
                    <i class="fas fa-money-check-alt"></i>
                    <div class="count">€ @ViewBag.receita</div>
                    <div class="title">Receita</div>
                </div>
            </div>


            @if (User.IsInRole("Administrador"))
            {
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <div class="info-box orange-bg">
                        <i class="far fa-file-alt"></i>
                        <div class="count">@ViewBag.reclamacoes</div>
                        <div class="title">Novas Reclamações</div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <div class="info-box orange-bg">
                        <i class="far fa-file-alt"></i>
                        <div class="count">@ViewBag.reclamacoesfechadas</div>
                        <div class="title">Reclamações Resolvidas</div>
                    </div>
                </div>
            }


            @if (User.IsInRole("Operador"))
            {

                <div> <h1 style="text-align:center">Os meus números</h1></div>


                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="info-box linkedin-bg">
                        <div class="title">Número contratos</div>
                        <i class="fas fa-check"></i>
                        <div class="count"> @ViewBag.Meuscontratos</div>

                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <div class="info-box orange-bg">
                        <i class="far fa-file-alt"></i>
                        <div class="count">@ViewBag.reclamacoes</div>
                        <div class="title">Novas Reclamações</div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <div class="info-box orange-bg">
                        <i class="far fa-file-alt"></i>
                        <div class="count">@ViewBag.reclamacoesfechadas</div>
                        <div class="title">Reclamações Resolvidas</div>
                    </div>
                </div>



                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="info-box teal-bg">
                        <div class="title">Faturação</div>
                        <i class="fas fa-calculator"></i>
                        <div class="count"> € @ViewBag.faturacao</div>
                    </div>
                </div>
                @if (ViewBag.reclamacoes > 0)
                {
                    @await Component.InvokeAsync("Notyf")
                }

            }

        </div>

        <div class="row">
            <h4 style="text-align:center">Contamos consigo todos os dias para aumentar estes números. Bom trabalho!</h4>
        </div>
    </section>
</section>