Models/Reclamacoes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Projeto_Lab_Web_Grupo3.Models
{
    public class Reclamacoes
    {
        [Key]
        [Column("Reclamacao_Id")]
        public int ReclamacaoId { get; set; }

        [StringLength(1000)]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data de Reclamação")]
        public DateTime DataReclamacao { get; set; }

        [Display(Name = "Resposta do Operador")]
        public string Resposta { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data de Resposta")]
        public DateTime DataResposta { get; set; }
        [Display(Name = "Respondido")]
        public bool EstadoResposta { get; set; }

        public int ContratoId { get; set; }
        [Display(Name = "Resolvido")]
        public bool EstadoResolução { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data de Resolução")]
        public DateTime DataResolucao { get; set; }

        public int ClienteId { get; set; }

        public int FuncionarioId { get; set; }



        [ForeignKey(nameof(ClienteId))]
        [InverseProperty(nameof(Utilizadores.ReclamacoesCliente))]
        public virtual Utilizadores Cliente { get; set; }

        [ForeignKey(nameof(FuncionarioId))]
        [InverseProperty(nameof(Utilizadores.ReclamacoesFuncionario))]
        public virtual Utilizadores Funcionario { get; set; }
        [Display(Name ="Arquivado")]
        public bool Inactivo { get; set; }


        [ForeignKey(nameof(ContratoId))]
        [InverseProperty("Reclamacao")]
        public virtual Contratos Contratos { get; set; }
    }
}

Models/ReclamacoesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Projeto_Lab_Web_Grupo3.Models
{
    public class ReclamacoesViewModel
    {
        public List <Reclamacoes> Reclamacoes { get; set; }
        public int ReclamacaoId { get; set; }
        public Paginacao Paginacao { get; set; }
        [StringLength(1000)]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Data de Reclamação")]
        public DateTime DataReclamacao { get; set; }
        [Display(Name = "Resposta do Operador")]
        public string Resposta { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Data de Resposta")]
        public DateTime DataResposta { get; set; }

        public bool EstadoResposta { get; set; }
        [Display(Name = "Resolvido")]
        public bool EstadoResolução { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Data de Resolução")]
        public DateTime DataResolucao { get; set; }

        public int ClienteId { get; set; }

        public int FuncionarioId { get; set; }
        [Display(Name = "Arquivado")]
        public bool Inactivo { get; set; }
        public int ContratoId { get; set; }
        public string NifPesquisar { get; set; }
        public string NomePesquisar { get; set; }

        [ForeignKey(nameof(ClienteId))]
        [InverseProperty(nameof(Utilizadores.ReclamacoesCliente))]
        public virtual Utilizadores Cliente { get; set; }

        [ForeignKey(nameof(FuncionarioId))]
        [InverseProperty(nameof(Utilizadores.ReclamacoesFuncionario))]
        public virtual Utilizadores Funcionario { get; set; }
        [ForeignKey(nameof(ContratoId))]
        [InverseProperty("Reclamacao")]
        public virtual Contratos Contratos { get; set; }
    }
}

Controllers/ReclamacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projeto_Lab_Web_Grupo3.Data;
using Projeto_Lab_Web_Grupo3.Models;
using AspNetCoreHero.ToastNotification;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace Projeto_Lab_Web_Grupo3.Controllers
{
    public class ReclamacoesController : Controller
    {
        private readonly Projeto_Lab_WebContext bd;

        public ReclamacoesController(Projeto_Lab_WebContext context)
        {
            bd = context;
        }

        // GET: Reclamacoes
        public async Task<IActionResult> Index(string nomePesquisar, int pagina = 1)
        {




            Paginacao paginacao = new Paginacao
            {
                TotalItems = await bd.Reclamacoes

                            .CountAsync(),
                PaginaAtual = pagina
            };

            List<Reclamacoes> reclamacoes = await bd.Reclamacoes.Where(p => nomePesquisar == null || p.Cliente.Nome.Contains(nomePesquisar) || p.Cliente.Nif.Contains(nomePesquisar))
                .Include(p => p.Cliente)
                .Where(p => p.Inactivo == false)
                  .OrderBy(p => p.Cliente.Nome)

                .Skip(paginacao.ItemsPorPagina * (pagina - 1))
                .Take(paginacao.ItemsPorPagina)
                .ToListAsync();


            ReclamacoesViewModel modelo = new ReclamacoesViewModel
            {
                Paginacao = paginacao,
                Reclamacoes = reclamacoes,
                NomePesquisar = nomePesquisar
            };

            return base.View(modelo);
        }
        public async Task<IActionResult> ArquivadoOperador(string nomePesquisar, int pagina = 1)
        {

            Paginacao paginacao = new Paginacao
            {
                TotalItems = await bd.Reclamacoes

                         .CountAsync(),
                PaginaAtual = pagina
            };

            List<Reclamacoes> reclamacoes = await bd.Reclamacoes.Where(p => p.Inactivo == true || p.Cliente.Nome.Contains(nomePesquisar) || p.Cliente.Nif.Contains(nomePesquisar))
                 .Include(p => p.Cliente)
                  .OrderBy(p => p.Cliente.Nome)

                .Skip(paginacao.ItemsPorPagina * (pagina - 1))
                .Take(paginacao.ItemsPorPagina)
                .ToListAsync();


            ReclamacoesViewModel ArquivadoOperador = new ReclamacoesViewModel
            {
                Paginacao = paginacao,
                Reclamacoes = reclamacoes,
                NomePesquisar = nomePesquisar
            };

            return View(ArquivadoOperador);
        }

        // GET: Reclamacoes

        public async Task<IActionResult> ViewCliente()
        {


            List<Reclamacoes> ViewCliente = await bd.Reclamacoes

                .Include(p => p.Cliente).Where(p => p.Cliente.Email == User.Identity.Name)

                .ToListAsync();

            ReclamacoesViewModel viewCliente = new ReclamacoesViewModel
            {
                Reclamacoes = ViewCliente,
            };

            return View(viewCliente);
        }


        // GET: Reclamacoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reclamacoes = await bd.Reclamacoes
                .Include(r => r.Cliente)
                .Include(r => r.Funcionario)
                .FirstOrDefaultAsync(m => m.ReclamacaoId == id);
            if (reclamacoes == null)
            {
                return NotFound();
            }

            return View(reclamacoes);
        }

        // GET: Reclamacoes/Create

        [Authorize(Roles = "Cliente")]
        public IActionResult Create(int id)
        {
            ReclamacoesViewModel criar = new ReclamacoesViewModel();
            return View(criar);
        }

        // POST: Reclamacoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Cliente")]
        public async Task<IActionResult> Create(ReclamacoesViewModel reclamacoesViewModel, Reclamacoes reclamacao, int id)
        {
            if (ModelState.IsValid)
            {
                var cliente = bd.Utilizadores.SingleOrDefault(c => c.Email == User.Identity.Name);
                var contrato = bd.Contratos.SingleOrDefault(c => c.UtilizadorId == cliente.UtilizadorId);

                reclamacao.Cliente = cliente;

                reclamacao.ContratoId = contrato.ContratoId;
                reclamacao.FuncionarioId = contrato.FuncionarioId;

                reclamacao.EstadoResolução = false;
                reclamacao.EstadoResposta = false;
                reclamacao.DataReclamacao = DateTime.Now;

                reclamacao.Inactivo = false;
                reclamacao.Descricao = reclamacoesViewModel.Descricao;
                reclamacao.ReclamacaoId = reclamacoesViewModel.ReclamacaoId;


                bd.Add(reclamacao);
                await bd.SaveChangesAsync();

                ViewBag.Mensagem = "Reclamação enviada com sucesso";
                return View("Sucesso");
            }



            return View(reclamacao);
        }
        // GET: Reclamacao/RespostaOperador/5
        [Authorize(Roles = "Operador")]
        public async Task<IActionResult> RespostaOperador(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ReclamacoesViewModel reclamacoesViewModel = new ReclamacoesViewModel();
            var funcionario = await bd.Utilizadores.SingleOrDefaultAsync(c => c.Email == User.Identity.Name);
            var reclamacao = await bd.Reclamacoes
                .AsNoTracking()
                .SingleOrDefaultAsync(p => p.ReclamacaoId == id);
            reclamacoesViewModel.ReclamacaoId = reclamacao.ReclamacaoId;
            reclamacoesViewModel.ContratoId = reclamacao.ContratoId;
            reclamacoesViewModel.ClienteId = reclamacao.ClienteId;
            reclamacoesViewModel.Resposta = reclamacao.Resposta;


            reclamacoesViewModel.EstadoResposta = reclamacao.EstadoResposta;
            reclamacoesViewModel.EstadoResolução = reclamacao.EstadoResolução;







            if (reclamacao == null)
            {
                return NotFound();
            }
            ViewData["ContratoId"] = new SelectList(bd.Contratos, "ContratoId", "ContratoId", reclamacoesViewModel.ContratoId);
            return View(reclamacoesViewModel);

        }
        // POST: Reclamacao/RespostaReclamacaoOperador/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Operador")]
        public async Task<IActionResult> RespostaOperador(int id, ReclamacoesViewModel reclamacoesViewModel)
        {
            if (id != reclamacoesViewModel.ReclamacaoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var reclamacao = await bd.Reclamacoes
                        .AsNoTracking()
                        .SingleOrDefaultAsync(p => p.ReclamacaoId == id);

                    var funcionario = await bd.Utilizadores.SingleOrDefaultAsync(c => c.Email == User.Identity.Name);

                    reclamacao.ReclamacaoId = reclamacoesViewModel.ReclamacaoId;

                    reclamacoesViewModel.ClienteId = reclamacao.ClienteId;
                    reclamacao.FuncionarioId = funcionario.UtilizadorId;
                    reclamacao.ContratoId = reclamacao.ContratoId;
                    reclamacao.Resposta = reclamacoesViewModel.Resposta;
                    reclamacao.EstadoResposta = reclamacoesViewModel.EstadoResposta;
                    reclamacao.EstadoResolução = reclamacoesViewModel.EstadoResolução;
                    reclamacao.DataResposta = DateTime.Now;
                    reclamacao.DataResolucao = DateTime.Now;

                    bd.Reclamacoes.Update(reclamacao);
                    await bd.SaveChangesAsync();



                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReclamacoesExists(reclamacoesViewModel.ReclamacaoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.Mensagem = "Resposta enviada com sucesso";
                return View("SucessoOperador");
            }


            ModelState.AddModelError("", "Não foi possível registar a reclamação, tente novamente");
            return View(reclamacoesViewModel);
        }

        // GET: Reclamacoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reclamacoes = await bd.Reclamacoes.FindAsync(id);
            if (reclamacoes == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(bd.Utilizadores, "UtilizadorId", "Nome", reclamacoes.ClienteId);
            ViewData["FuncionarioId"] = new SelectList(bd.Utilizadores, "UtilizadorId", "Nome", reclamacoes.FuncionarioId);
            return View(reclamacoes);
        }

        // POST: Reclamacoes/Edit/5

Views/Reclamacoes/ArquivadoOperador.cshtml
@model ReclamacoesViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "_LayoutAdmin";
}


    <section id="container" class="">
        <section id="main-content">
            <section class="wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <h3 class="page-header"><i class="fa fa-inbox" aria-hidden="true"></i>Reclamações Arquivadas</h3>
                            <div class="card border-info mb-4">
                                <div class="card-body">


                                </div>
                            </div>

                            <div>
                                <br />
                                <div class="col-md-8 border-info mb-4">
                                    <div class="card-body">
                                        <h5 class="card-title" style="color:darkgrey">Pesquisar Reclamações (Por Nome/NIF)</h5>
                                        <form asp-action="Index" method="get">
                                            <div class="form-group">
                                                <input name="nomePesquisar" class="form-control" type="search" value="@Model.NomePesquisar" />
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" value="Pesquisar" class="btn btn-success btn-lg" />
                                                <a asp-action="Index" class="btn btn-primary btn-lg">Limpar</a>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>




                            <table class="table table-striped table-advance table-hover">
                                <thead>
                                    <tr>



                                        <th>
                                            @Html.DisplayNameFor(model => model.Descricao)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.DataReclamacao)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Cliente)
                                        </th>







                                    <tr />


                                </thead>
                                <tbody>

                                    @foreach (var item in Model.Reclamacoes)
                                    {
                                        <tr>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.Descricao)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DataReclamacao)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Cliente.Nome)
                                            </td>




                                            <td>


                                                <a asp-action="Details" asp-route-id="@item.ReclamacaoId">Detalhes</a> 



                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>




                            <nav>
                                <ul class="pagination justify-content-end">
                                    @{ int paginaInicial = Model.Paginacao.PaginaAtual - Paginacao.NUMERO_PAGINAS_MOSTRAR_ANTES_DEPOIS;
                                        if (paginaInicial < 1)
                                        {
                                            paginaInicial = 1;
                                        }

                                        int paginaFinal = Model.Paginacao.PaginaAtual + Paginacao.NUMERO_PAGINAS_MOSTRAR_ANTES_DEPOIS;
                                        if (paginaFinal > Model.Paginacao.TotalPaginas)
                                        {
                                            paginaFinal = Model.Paginacao.TotalPaginas;
                                        } }

                                    <li class="page-item @(Model.Paginacao.PaginaAtual == 1 ? "disabled" : "")">
                                        <a class="page-link" asp-action="Index" asp-route-pagina="1" asp-route-nomePesquisar="@Model.NomePesquisar">Primeiro</a>
                                    </li>

                                    @for (int i = paginaInicial; i <= paginaFinal; i++)
                                    {
                                        <li class="page-item @(Model.Paginacao.PaginaAtual == i ? "active" : "")">
                                            <a class="page-link" asp-action="Index" asp-route-pagina="@i" asp-route-nomePesquisar="@Model.NomePesquisar">@i</a>
                                        </li>
                                    }


                                    <li class="page-item @(Model.Paginacao.PaginaAtual == Model.Paginacao.TotalPaginas  ? "disabled" : "")">
                                        <a class="page-link" asp-action="Index" asp-route-pagina="@Model.Paginacao.TotalPaginas" asp-route-nomePesquisar="@Model.NomePesquisar">Último</a>
                                    </li>
                                </ul>
                            </nav>



                        </section>
                    </div>
                </div>
            </section>
        </section>
    </section>

Views/Reclamacoes/Create.cshtml
@model Projeto_Lab_Web_Grupo3.Models.ReclamacoesViewModel

@{
    ViewData["Title"] = "Criar";
    Layout =  "_LayoutPData"; ;
}
<section id="main-content">              
                <form asp-action="Create" class="form-horizontal">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                            
                        <div class="container bg-white mt-5 mb-5">
                            <div class="p-3 m-t-25 py-5">
                                <div class="align-items-center">
                                    <h4 class="text-center">Reclamação  <i class="far fa-frown-open"></i></h4>
                                </div>
                                <p>Na RD Telecom, o que mais valorizamos é a sua satisfação como cliente. </p>
                                <p>Caso tenha uma reclamação a fazer indique na caixa de texto em baixo e os nossos colaboradores irão resolver a sua situação o mais breve possivel. Obrigado! </p>
                                <div class="row offset-2">
                                    <div class="col-lg-9">      
                                        <div class="form-group">
                                            <p>Enviar nova reclamação:</p>
                                            <label for="exampleFormControlTextarea1" class="col-sm-2 control-label" asp-for="Descricao"></label>
                                            <div class="col-lg-9">
                                                <textarea type="text" id="exampleFormControlTextarea1" rows="3" asp-for="Descricao" class="form-control"></textarea>
                                                <span asp-validation-for="Descricao" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="offset-2">
                                            <input type="submit" class="button-form-btn3" value="Enviar Reclamação" />
                                            <a class="button-form-btn4" asp-controller="Reclamacoes" asp-action="ViewCliente">Cancelar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>                                     
                </form>     
 </section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reclamacoes/Delete.cshtml
@model Projeto_Lab_Web_Grupo3.Models.Reclamacoes

@{
    ViewData["Title"] = "Delete";
    Layout = "_LayoutPData";
}

<container>
    <div class="container bg-white mt-5">
        <div class="row offset-2">
            <div class="col-lg-12">
                <div class="p-3 m-t-25 py-5">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4 class="text-right">Arquivar Reclamação</h4>
                    </div>
                    <div class="row">
                        <div class="col-lg-10">
                            <section class="panel">
                                <table class="table table-bordered">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Descricao)
                                        </th>
                                        <td>
                                            @Html.DisplayFor(model => model.Descricao)
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.DataReclamacao)
                                        </th>
                                        <td>
                                            @Html.DisplayFor(model => model.DataReclamacao)
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Resposta)
                                        </th>
                                        <td>
                                            @Html.DisplayFor(model => model.Resposta)
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.DataResposta)
                                        </th>
                                        <td>
                                            @Html.DisplayFor(model => model.DataResposta)
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.EstadoResposta)
                                        </th>

                                        @if (Model.EstadoResposta == true)
                                        {
                                            <td class="col-lg-7">
                                                Sim
                                            </td>
                                        }
                                        else
                                        {
                                            <td class="col-lg-7">
                                                Não
                                            </td>
                                        }



                                    </tr>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.EstadoResolução)
                                        </th>
                                        @if (Model.EstadoResolução == true)
                                        {
                                            <td class="col-lg-7">
                                                Sim
                                            </td>
                                        }
                                        else
                                        {
                                            <td class="col-lg-7">
                                                Não
                                            </td>
                                        }
                                    </tr>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.DataResolucao)
                                        </th>
                                        <td>
                                            @Html.DisplayFor(model => model.DataResolucao)
                                        </td>
                                    </tr>



                                </table>
                                <div class="row">                                    
                                <form asp-action="Delete">
                                    <input type="hidden" asp-for="ReclamacaoId" />
                                    <input type="submit" value="Marcar Como Resolvida" class="button-form-btn2 col-lg-4" />
                                    <a asp-area="" asp-controller="Reclamacoes" asp-action="Create" class="button-form-btn2 col-lg-4">Enviar nova reclamação</a>
                                    <a asp-action="ViewCliente" class="button-form-btn4 col-lg-4 offset-1">Cancelar</a>
                                </form>
                                        </div>                                    
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</container>

Views/Reclamacoes/Sucesso.cshtml
@{
    Layout = "_LayoutPData"; ;
}

<body>
    <!-- container section start -->
    <section id="container" class="">
        <section id="main-content">
            <section class="wrapper">
                <div class="row offset-2 mb-5">
                    <div class="col-lg-7 mb-5">
                        <div class="p-3 py-5 mb-5">
                            <div class="d-flex justify-content-between align-items-center mb-5">
                                <p class="card-text">@ViewBag.Mensagem</p>
                            </div>
                            
                            <a class="button-form-btn2 mb-5" asp-controller="Reclamacoes" asp-action="ViewCliente">Voltar às Reclamações</a>
                        </div>
                    </div>
                </div>                
            </section>
        </section>
    </section>
</body>

Views/Reclamacoes/SucessoOperador.cshtml
@{
    Layout = "_LayoutAdmin"; 
}
<body>
    <!-- container section start -->
    <section id="container" class="">
        <section id="main-content">
            <section class="wrapper">
                <div class="row offset-3">
                    <div class="col-lg-7">
                        <div class="p-3 py-5">
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <p class="card-text">@ViewBag.Mensagem</p>
                            </div>

                            <a class="btn btn-primary" asp-controller="Reclamacoes" asp-action="Index">Voltar às Reclamações</a>
                        </div>
                    </div>
                </div>
            </section>
        </section>
    </section>
</body>